# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x VUE2/gradlew
    - name: Update version for CI snapshot
      run: .github/workflows/make-snapshot-version.sh
    - name: Build with Gradle
      working-directory: VUE2
      run: ./gradlew build
    - name: Upload jar
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: VUE2/build/libs
    - name: Upload bundles
      uses: actions/upload-artifact@v1
      with:
        name: bundles
        path: VUE2/build/distributions
